package com.codereviewer.ai;

import com.codereviewer.model.codeIssue;
import com.codereviewer.utils.PromptBuilder;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.List;

public class AIReviewer {


// Ollama local API
private static final String OLLAMA_URL =
        "http://localhost:11434/api/generate";

// Qwen2.5-Coder 1.5B
private static final String MODEL =
        "qwen2.5-coder:1.5b";

private final HttpClient httpClient;

public AIReviewer() {
    this.httpClient = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(30))
            .build();
}

/**
 * Sends Java source code and static-analysis findings
 * to PromptBuilder and then to Ollama/Qwen.
 *
 * @param sourceCode   Java source code being reviewed
 * @param staticIssues findings generated by the static analyzers
 * @return AI-generated review
 */
public String review(
        String sourceCode,
        List<codeIssue> staticIssues) {

    // Build the prompt using your existing PromptBuilder
    String prompt = PromptBuilder.build(
            sourceCode,
            staticIssues
    );

    // Send the prompt to Ollama
    return sendToOllama(prompt);
}

/**
 * Sends a prompt to the Ollama API.
 */
private String sendToOllama(String prompt) {

    try {

        String jsonBody = """
                {
                    "model": "%s",
                    "prompt": "%s",
                    "stream": false
                }
                """.formatted(
                        MODEL,
                        escapeJson(prompt)
                );

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(OLLAMA_URL))
                .header(
                        "Content-Type",
                        "application/json"
                )
                .timeout(Duration.ofMinutes(5))
                .POST(
                        HttpRequest.BodyPublishers.ofString(
                                jsonBody
                        )
                )
                .build();

        HttpResponse<String> response =
                httpClient.send(
                        request,
                        HttpResponse.BodyHandlers.ofString()
                );

        if (response.statusCode() != 200) {

            throw new RuntimeException(
                    "Ollama returned HTTP "
                            + response.statusCode()
                            + ": "
                            + response.body()
            );
        }

        return extractResponse(response.body());

    } catch (IOException e) {

        throw new RuntimeException(
                "Could not connect to Ollama. "
                        + "Make sure Ollama is running.",
                e
        );

    } catch (InterruptedException e) {

        Thread.currentThread().interrupt();

        throw new RuntimeException(
                "Request to Ollama was interrupted.",
                e
        );
    }
}

/**
 * Escapes special characters so the prompt
 * can safely be placed inside JSON.
 */
private String escapeJson(String text) {

    return text
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t");
}

/**
 * Extracts the "response" value from Ollama's
 * JSON response.
 */
private String extractResponse(String json) {

    String key = "\"response\":\"";

    int start = json.indexOf(key);

    if (start == -1) {
        return json;
    }

    start += key.length();

    StringBuilder result =
            new StringBuilder();

    boolean escaped = false;

    for (int i = start; i < json.length(); i++) {

        char c = json.charAt(i);

        if (escaped) {

            switch (c) {

                case 'n':
                    result.append('\n');
                    break;

                case 'r':
                    result.append('\r');
                    break;

                case 't':
                    result.append('\t');
                    break;

                case '"':
                    result.append('"');
                    break;

                case '\\':
                    result.append('\\');
                    break;

                default:
                    result.append(c);
            }

            escaped = false;

        } else if (c == '\\') {

            escaped = true;

        } else if (c == '"') {

            break;

        } else {

            result.append(c);
        }
    }

    return result.toString();
}

/**
 * Simple test for Ollama + Qwen.
 *
 * This can be removed later when Main.java
 * controls the application.
 */
public static void main(String[] args) {

    AIReviewer reviewer =
            new AIReviewer();

    String sourceCode = """
            public class TestCode {

                public void test() {

                    int a = 10;
                    int b = 0;

                    int result = a / b;

                    System.out.println(result);
                }
            }
            """;

    // Empty list for the initial Ollama test.
    // Later this will come from your static analyzers.
    List<codeIssue> staticIssues =
            List.of();

    try {

        String review =
                reviewer.review(
                        sourceCode,
                        staticIssues
                );

        System.out.println();
        System.out.println(
                "========================================"
        );
        System.out.println(
                "          AI CODE REVIEW"
        );
        System.out.println(
                "========================================"
        );
        System.out.println();

        System.out.println(review);

    } catch (RuntimeException e) {

        System.err.println();
        System.err.println(
                "AI Reviewer Error:"
        );
        System.err.println(
                e.getMessage()
        );
    }
}

}

